export const usuarios = [
  {
    name: "Alejandro García",
    age: 45,
    email: "alejandro.garcia@example.com",
    pass: "clave123",
    role: "admin",
  },
  {
    name: "Laura Martínez",
    age: 32,
    email: "laura.martinez@example.com",
    pass: "password2024",
    role: "user",
  },
  {
    name: "Carlos Pérez",
    age: 28,
    email: "carlos.perez@example.com",
    pass: "segura456",
    role: "user",
  },
  {
    name: "María López",
    age: 38,
    email: "maria.lopez@example.com",
    pass: "contraseña789",
    role: "admin",
  },
  {
    name: "Javier Torres",
    age: 22,
    email: "javier.torres@example.com",
    pass: "javi2025",
    role: "user",
  },
  {
    name: "Elena Ruiz",
    age: 30,
    email: "elena.ruiz@example.com",
    pass: "elenaPass",
    role: "user",
  },
  {
    name: "Roberto Sánchez",
    age: 41,
    email: "roberto.sanchez@example.com",
    pass: "rsanchez123",
    role: "admin",
  },
  {
    name: "Sofía Herrera",
    age: 27,
    email: "sofia.herrera@example.com",
    pass: "sofiaSecure",
    role: "user",
  },
];
